name: ci
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
    tags:
      - '*'

jobs:
  build:
    strategy:
      matrix:
        fedora:
          - 33-1.2
          - 34-1.2
          - 35-1.2
    env:
      MAKE: make FEDORA_VERSION=${{ matrix.fedora }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get Fedora version
        run: echo "FEDORA_MAJOR=$(${MAKE} show-fedora-major)" >> ${GITHUB_ENV}

      - name: Build builder image
        run: ${MAKE} builder
      - name: Build updater image
        run: ${MAKE} updater

      - name: Login to GitHub Container Registry
        if: github.event_name == 'push'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.SQBOT_GITHUB_TOKEN }}
      - name: Upload to GitHub Container Registry (latest)
        if: github.ref == 'refs/heads/main'
        run: |
          docker tag \
            tmprootfs-fedora-builder:${FEDORA_MAJOR} \
            ghcr.io/seqsense/tmprootfs-fedora-builder:${FEDORA_MAJOR}
          docker tag \
            tmprootfs-fedora-updater:${FEDORA_MAJOR} \
            ghcr.io/seqsense/tmprootfs-fedora-updater:${FEDORA_MAJOR}
          docker push ghcr.io/seqsense/tmprootfs-fedora-builder:${FEDORA_MAJOR}
          docker push ghcr.io/seqsense/tmprootfs-fedora-updater:${FEDORA_MAJOR}
      - name: Upload to GitHub Container Registry (tag)
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          tag=${FEDORA_MAJOR}-${GITHUB_REF#refs/tags/}
          docker tag \
            tmprootfs-fedora-builder:${FEDORA_MAJOR} \
            ghcr.io/seqsense/tmprootfs-fedora-builder:${tag}
          docker tag \
            tmprootfs-fedora-updater:${FEDORA_MAJOR} \
            ghcr.io/seqsense/tmprootfs-fedora-updater:${tag}
          docker push ghcr.io/seqsense/tmprootfs-fedora-builder:${tag}
          docker push ghcr.io/seqsense/tmprootfs-fedora-updater:${tag}
