name: ci
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        fedora:
          - 33-1.2
          - 34-1.2
          - 35-1.2
    env:
      MAKE: make FEDORA_VERSION=${{ matrix.fedora }}
    runs-on: ubuntu-latest
    steps:
      - name: Select mirror
        run: |
          for url in \
            https://mirror.genesisadaptive.com/fedora/linux \
            http://mirror.math.princeton.edu/pub/fedora/linux
          do
            echo "Trying ${url}"
            if (curl --fail -L --connect-timeout 5 ${url} > /dev/null 2> /dev/null)
            then
              echo "FEDORA_MIRROR=${url}" >> ${GITHUB_ENV}
              exit 0
            fi
          done
          echo "No mirror is available"
          false

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get Fedora version
        run: echo "FEDORA_MAJOR=$(${MAKE} show-fedora-major)" >> ${GITHUB_ENV}

      - name: Build builder image
        run: ${MAKE} builder FEDORA_MIRROR=${FEDORA_MIRROR}
      - name: Build updater image
        run: ${MAKE} updater FEDORA_MIRROR=${FEDORA_MIRROR}

      - name: Login to GitHub Container Registry
        if: github.event_name == 'push'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.SQBOT_GITHUB_TOKEN }}
      - name: Upload to GitHub Container Registry
        if: github.event_name == 'push'
        run: |
          docker tag \
            tmprootfs-fedora-builder:${FEDORA_MAJOR} \
            ghcr.io/seqsense/tmprootfs-fedora-builder:${FEDORA_MAJOR}
          docker tag \
            tmprootfs-fedora-updater:${FEDORA_MAJOR} \
            ghcr.io/seqsense/tmprootfs-fedora-updater:${FEDORA_MAJOR}
          docker push ghcr.io/seqsense/tmprootfs-fedora-builder:${FEDORA_MAJOR}
          docker push ghcr.io/seqsense/tmprootfs-fedora-updater:${FEDORA_MAJOR}
